### ISSUE TITLE
How it it different or better from applying backtracking algorithm?

### ISSUE THREAD

**Issue by shivakrishna9** [Kyubyong/sudoku#6]
We arrive at solutions in less time by backtracking also. In this sense , I want to ask that are there any practical implications for this neural net ?

By the way, I am beginner in deep learning.

**Comment by Kyubyong** [comment]
My answer is "nothing". I mean, this project is not designed to solve Sudoku better than other approaches. Rather, my goal is to find out neural networks can be applied to Sudoku solving.

**Comment by shivakrishna9** [comment]
Yeah.I understood that. I asked just to confirm. By the way nice attempt.
